In [105]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import MissingIndicator,SimpleImputer

In [106]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [107]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [108]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [109]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [83]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

In [84]:
X_train.head()

Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

In [85]:
X_train.isnull().mean()

Age     0.207865
Fare    0.000000
dtype: float64

In [86]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [87]:
X_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]])

In [88]:
np.isnan(X_train_trf)

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [89]:
from sklearn.linear_model import LogisticRegression

In [90]:
X_test_trf.shape

(179, 2)

In [91]:
X_train.isnull().sum()

Age     148
Fare      0
dtype: int64

In [92]:
clf = LogisticRegression()
a = clf.fit(X_train_trf,y_train)
y_pred = clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

In [93]:
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0], dtype=int64)

In [94]:
mi = MissingIndicator()
X_train_missing = mi.fit_transform(X_train)
X_test_missing = mi.fit_transform(X_test)

In [95]:
mi.features_

array([0], dtype=int64)

In [96]:
X_train['Age_NA'] = X_train_missing
X_test['Age_NA'] = X_test_missing

In [97]:
si = SimpleImputer()
X_train_trf3 = si.fit_transform(X_train)
X_test_trf3 = si.fit_transform(X_test)

In [98]:
from sklearn.linear_model import LogisticRegression

In [99]:
clf = LogisticRegression()
clf.fit(X_train_trf3,y_train)

y_pred=clf.predict(X_test_trf3)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred) 

0.6312849162011173

Filling missing values with Sklearn

In [110]:
si = SimpleImputer(add_indicator=True)

In [111]:
X_train = si.fit_transform(X_train)

In [114]:
np.isnan(X_train).any() 

False

In [115]:

X_test = si.transform(X_test)

In [125]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173